const rooms = [
  {
    id: 1,
    roomName: 'Deluxe Room',
    img: 'https://themes.pixelstrap.com/rica/assets/images/hotel/gallery/1.jpg',
    amenities: ['King/Twin', 'Shower', 'LCD TV', 'Couch'],
    inclusion: ['Wi-Fi', 'Breakfast', 'Non Refundable'],
    reviews: 'Aquí deben ir las reviews del hotel o hacerlo en la tabla de hoteles mejor',
    labels: 'Recuerda colocar un array con los labels del hotel',
    newPrice: 1000,
    previousPrice: 1250,
    basicRoomPrice: 250,
    locationTags: 'Mina Road, Bur Dubai, Dubai, United Arab Emirates',
    country: 'United States',
    city: 'New York',
    hotelName: 'Paradise',
    guests: 3,
    checkIn: '2:00 p.m',
    checkOut: '12:00 p.m',
    dateIn: '12/08/2023',
    dateOut: '15/08/2023',
  },
  {
    id: 2,
    roomName: 'Suite Room',
    img: 'https://themes.pixelstrap.com/rica/assets/images/hotel/room/5.jpg',
    amenities: ['King/Twin', 'Shower', 'LCD TV', 'Pool View'],
    inclusion: ['Wi-Fi', 'Breakfast', 'Free Cancellation'],
    reviews: 'Aquí deben ir las reviews del hotel o hacerlo en la tabla de hoteles mejor',
    labels: 'Recuerda colocar un array con los labels del hotel',
    newPrice: 1100,
    previousPrice: 1350,
    basicRoomPrice: 250,
    locationTags: 'Mina Road, Bur Dubai, Dubai, United Arab Emirates',
    country: 'Italy',
    city: 'Rome',
    hotelName: 'Landscape',
    guests: 4,
    checkIn: '1:00 p.m',
    checkOut: '3:00 p.m',
    dateIn: '15/07/2023',
    dateOut: '20/07/2023',
  },
  {
    id: 3,
    roomName: 'Royal Room',
    img: 'https://themes.pixelstrap.com/rica/assets/images/hotel/room/6.jpg',
    amenities: ['King/Twin', 'Pool View', 'LCD TV', 'Couch'],
    inclusion: ['Wi-Fi', 'Breakfast', 'Dinner & Lunch'],
    reviews: 'Aquí deben ir las reviews del hotel o hacerlo en la tabla de hoteles mejor',
    labels: 'Recuerda colocar un array con los labels del hotel',
    newPrice: 1800,
    previousPrice: 1950,
    basicRoomPrice: 250,
    locationTags: 'Mina Road, Bur Dubai, Dubai, United Arab Emirates',
    country: 'Argentina',
    city: 'Buenos Aires',
    hotelName: 'Pampalare',
    guests: 2,
    checkIn: '2:00 p.m',
    checkOut: '12:00 p.m',
    dateIn: '1/08/2023',
    dateOut: '5/08/2023',
  },
];
export default rooms;
