const hotels = [
  {
    id: 1,
    name: 'The Venetian',
    img: 'https://themes.pixelstrap.com/rica/assets/images/hotel/gallery/1.jpg',
    city: 'New York',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac est ut est vehicula interdum quis eget odio. Nam commodo nisi eu dui vulputate luctus. Praesent aliquet justo nec facilisis ultrices. Donec a venenatis mauris, et rutrum elit. Sed eleifend ipsum vel dapibus dapibus. Nullam id nulla ut odio euismod aliquet. Mauris non arcu nec dui facilisis vehicula. Aenean vel magna nec erat tincidunt iaculis vitae ac mauris.',
    review: '26412 review',
    newPrice: 1000,
    previousPrice: 1300,
    labels1: 'Victor',
    labels2: 'Parking',
    status: 'Recommended',
  },
  {
    id: 2,
    name: 'The Mirage',
    img: 'https://themes.pixelstrap.com/rica/assets/images/hotel/video-image.jpg',
    city: 'New York',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac est ut est vehicula interdum quis eget odio. Nam commodo nisi eu dui vulputate luctus. Praesent aliquet justo nec facilisis ultrices. Donec a venenatis mauris, et rutrum elit. Sed eleifend ipsum vel dapibus dapibus. Nullam id nulla ut odio euismod aliquet. Mauris non arcu nec dui facilisis vehicula. Aenean vel magna nec erat tincidunt iaculis vitae ac mauris.',
    review: '26412 review',
    newPrice: 1245,
    previousPrice: 1300,
    labels1: 'Swimming',
    labels2: 'Parking',
    status: 'Para victor',
  },
  {
    id: 3,
    name: 'The Wynn',
    img: 'https://themes.pixelstrap.com/rica/assets/images/hotel/room/3.jpg',
    city: 'New York',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac est ut est vehicula interdum quis eget odio. Nam commodo nisi eu dui vulputate luctus. Praesent aliquet justo nec facilisis ultrices. Donec a venenatis mauris, et rutrum elit. Sed eleifend ipsum vel dapibus dapibus. Nullam id nulla ut odio euismod aliquet. Mauris non arcu nec dui facilisis vehicula. Aenean vel magna nec erat tincidunt iaculis vitae ac mauris.',
    review: '26412 review',
    newPrice: 1245,
    previousPrice: 1300,
    labels1: 'Swimming',
    labels2: 'Parking',
    status: 'Recommended',
  },
  {
    id: 4,
    name: 'The Aria',
    img: 'https://themes.pixelstrap.com/rica/assets/images/hotel/gallery/3.jpg',
    city: 'New York',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac est ut est vehicula interdum quis eget odio. Nam commodo nisi eu dui vulputate luctus. Praesent aliquet justo nec facilisis ultrices. Donec a venenatis mauris, et rutrum elit. Sed eleifend ipsum vel dapibus dapibus. Nullam id nulla ut odio euismod aliquet. Mauris non arcu nec dui facilisis vehicula. Aenean vel magna nec erat tincidunt iaculis vitae ac mauris.',
    review: '26412 review',
    newPrice: 1245,
    previousPrice: 1300,
    labels1: 'Swimming',
    labels2: 'Parking',
  },
  {
    id: 5,
    name: 'Mandalay Bay',
    img: 'https://themes.pixelstrap.com/rica/assets/images/hotel/gallery/5.jpg',
    city: 'New York',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac est ut est vehicula interdum quis eget odio. Nam commodo nisi eu dui vulputate luctus. Praesent aliquet justo nec facilisis ultrices. Donec a venenatis mauris, et rutrum elit. Sed eleifend ipsum vel dapibus dapibus. Nullam id nulla ut odio euismod aliquet. Mauris non arcu nec dui facilisis vehicula. Aenean vel magna nec erat tincidunt iaculis vitae ac mauris.',
    review: '26412 review',
    newPrice: 1245,
    previousPrice: 1300,
    labels1: 'Swimming',
    labels2: 'Parking',
    status: 'The best',
  },
  {
    id: 6,
    name: 'The Luxor',
    img: 'https://themes.pixelstrap.com/rica/assets/images/hotel/room/1.jpg',
    city: 'New York',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac est ut est vehicula interdum quis eget odio. Nam commodo nisi eu dui vulputate luctus. Praesent aliquet justo nec facilisis ultrices. Donec a venenatis mauris, et rutrum elit. Sed eleifend ipsum vel dapibus dapibus. Nullam id nulla ut odio euismod aliquet. Mauris non arcu nec dui facilisis vehicula. Aenean vel magna nec erat tincidunt iaculis vitae ac mauris.',
    review: '26412 review',
    newPrice: 1245,
    previousPrice: 1300,
    labels1: 'Swimming',
    labels2: 'Parking',
  },
  {
    id: 7,
    name: 'The Cosmopolitan',
    img: 'https://themes.pixelstrap.com/rica/assets/images/hotel/gallery/4.jpg',
    city: 'New York',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac est ut est vehicula interdum quis eget odio. Nam commodo nisi eu dui vulputate luctus. Praesent aliquet justo nec facilisis ultrices. Donec a venenatis mauris, et rutrum elit. Sed eleifend ipsum vel dapibus dapibus. Nullam id nulla ut odio euismod aliquet. Mauris non arcu nec dui facilisis vehicula. Aenean vel magna nec erat tincidunt iaculis vitae ac mauris.',
    review: '26412 review',
    newPrice: 1245,
    previousPrice: 1300,
    labels1: 'Swimming',
    labels2: 'Parking',
  },
  {
    id: 8,
    name: 'Royal Bridge',
    img: 'https://media-cdn.tripadvisor.com/media/photo-s/28/45/a9/2d/hermoso-lugar-muy-hermoso.jpg',
    city: 'Mongui',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac est ut est vehicula interdum quis eget odio. Nam commodo nisi eu dui vulputate luctus. Praesent aliquet justo nec facilisis ultrices. Donec a venenatis mauris, et rutrum elit. Sed eleifend ipsum vel dapibus dapibus. Nullam id nulla ut odio euismod aliquet. Mauris non arcu nec dui facilisis vehicula. Aenean vel magna nec erat tincidunt iaculis vitae ac mauris.',
    review: '26412 review',
    newPrice: 1245,
    previousPrice: 1300,
    labels1: 'Swimming',
    labels2: 'Parking',
  },

];

export default hotels;
